###  200 user ada, semua valid => dapet token
POST http://localhost:{{$dotenv PORT}}/api/auth/login HTTP/1.1
content-type: application/json

{
    "email": "maman@mail.co",
    "password": "password"
}

### 500 valid tapi user gaada
POST http://localhost:{{$dotenv PORT}}/api/auth/login HTTP/1.1
content-type: application/json

{
    "email": "dadang@mail.co",
    "password": "password"
}

### 400 salah banyak
POST http://localhost:{{$dotenv PORT}}/api/auth/login HTTP/1.1
content-type: application/json

{
    "email": "test@mail.com",
    "password": "fdafdsfaf"
}

### 400 pass don't match 
POST http://localhost:{{$dotenv PORT}}/api/auth/register HTTP/1.1
content-type: application/json

{
    "email": "test@mail.com",
    "password": "rahasya",
    "re_password": "rahasia"
}

### 400 user exists
POST http://localhost:{{$dotenv PORT}}/api/auth/register HTTP/1.1
content-type: application/json

{
    "email": "maman@mail.co",
    "password": "password",
    "re_password": "password"
}
### not null viloation
POST http://localhost:{{$dotenv PORT}}/api/auth/register HTTP/1.1
content-type: application/json

{
    "email": "reisya@mail.co",
    "password": "password",
    "re_password": "password"
}

### register success
POST http://localhost:{{$dotenv PORT}}/api/auth/register HTTP/1.1
content-type: application/json

{
    "email": "reisya@mail.co",
    "password": "password",
    "re_password": "password",
    "username": "icantik",
    "role": "renter"
}

### pass didn't match
POST http://localhost:{{$dotenv PORT}}/api/auth/login HTTP/1.1
content-type: application/json

{
    "email": "maman@mail.co",
    "password": "passwordd"
}

### with token depcreated
POST http://localhost:{{$dotenv PORT}}/api/auth/deserialize HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjozLCJlbWFpbCI6Im1hbWFuQG1haWwuY28iLCJ1c2VybmFtZSI6Im1hbWFuIn0sImlhdCI6MTU5MjI3MzMzMywiZXhwIjoxNTkyNzA1MzMzfQ.7-gNBs7YV7ZYVcCBpJVDGWLKnmlM00WZxmuHW3qhxHE

### with token deprecated
POST http://localhost:{{$dotenv PORT}}/api/auth/deserialize HTTP/1.1
Content-Type: application/json
Authorization: Bearer diacakacak.eyJ1c2VyIjp7ImlkIjoxLCJlbWFpbCI6Im1hbWFuQG1haWwuY28ifSwiaWF0IjoxNTkxOTc0NzM2LCJleHAiOjE1OTI0MDY3MzZ9.5RQPC0WvsUmMxLNQBVkmm1qkHPolcIZbyaPnuHCy7zc