
# @hostname = 68.183.183.98
@hostname = localhost
@port = 8080
@host = {{hostname}}:{{port}}

### user query venues
GET http://{{host}}/api/venues
?sortBy=rating

### user query venues
GET http://{{host}}/api/venues
?sortBy=price

### go to venue details
GET http://{{host}}/api/venues/1 HTTP/1.1

### venue has packages
GET http://{{host}}/api/venues/1/packages HTTP/1.1

### user query venues
GET http://{{host}}/api/venues/cities

### user detail (bonus: ada venue dianya juga)
GET http://{{host}}/api/users/4 HTTP/1.1

### detail paket
GET http://{{host}}/api/packages/2 HTTP/1.1

### cek packages yang tersedia pada venue tersebut
GET http://{{host}}/api/venues/2/available
?date=2020-06-19T00:00:00.000Z

### cek daftar reservasi user(column belum dirapihin)
GET http://{{host}}/api/users/3/reservations HTTP/1.1

### bikin reservasi, asumsi sekali request udah bayar
POST http://{{host}}/api/users/3/reservations
content-type: application/json

{
    "date": "2020-06-16T14:07:50.000Z",
    "packageId": 3,
    "numPeople": 100,
    "bank": "bni"
}

### cek daftar reservasi user(column belum dirapihin)
GET http://{{host}}/api/users/3/orders HTTP/1.1

### commenting
POST http://{{host}}/api/users/1/reviews
content-type: application/json

{
    "venueId": 3,
    "comment": "lol pls",
    "rating": 3
}

### wislists
GET http://{{host}}/api/users/1/wishlist HTTP/1.1

###
POST http://{{host}}/api/users/1/wishlist/venues
content-type: application/json

{
    "venueId": 2
}

###
DELETE http://{{host}}/api/users/1/wishlist/venues/1