###
POST https://api.sandbox.midtrans.com/v2/charge
Content-Type: application/json
Authorization: Basic U0ItTWlkLXNlcnZlci1mdTRKWmlsT1d0eU5xVjVUZDJPaFpSbUQ6Cg==
Accept: application/json

{
    "payment_type": "bank_transfer",
    "transaction_details": {
        "gross_amount": 5000000,
        "order_id": "fdffddfafdff"
    },
    "item_details": [
    {
       "id": "1",
       "price": 5000000,
       "name": "sunset apakcage",
       "quantity": 1
    }
   ],
   "bank_transfer":{
     "bank": "bni"
  },  "custom_expiry": {
      "expiry_duration": 60,
      "unit": "second"
  }
}

###
POST http://localhost:5000/api/midtrans/charge
Content-Type: application/json
Authorization: Basic U0ItTWlkLXNlcnZlci1mdTRKWmlsT1d0eU5xVjVUZDJPaFpSbUQ6Cg==
Accept: application/json

###
POST http://localhost:8080/api/midtrans/check
Content-Type: application/json
Authorization: Basic U0ItTWlkLXNlcnZlci1mdTRKWmlsT1d0eU5xVjVUZDJPaFpSbUQ6Cg==
Accept: application/json

{
    "transaction_id": "8b147102-84b4-4874-8755-728a648343f2"
}

###
POST http//localhost:8080/api/midtrans/receive_notif

{
  "va_numbers": [
    {
      "bank": "bca",
      "va_number": "55676095739"
    }
  ],
  "payment_amounts": [],
  "transaction_time": "2020-06-20 07:52:24",
  "gross_amount": "4200000.00",
  "currency": "IDR",
  "order_id": "8b147102-84b4-4874-8755-728a648343f2",
  "payment_type": "bank_transfer",
  "signature_key": "9da30873e374d5309292cdf00417c9e864dd0efb70c4b8a0977afff5e8a01a5cdbcd4878fa528a82d09197c9b945e505d70bb4d55814c7a6797d53fd4c60b6e9",
  "status_code": "407",
  "transaction_id": "ea2d5df0-7b27-4167-9ffd-adaaea1e7d2b",
  "transaction_status": "expire",
  "fraud_status": "accept",
  "status_message": "Success, transaction is found",
  "merchant_id": "G498255676"
}

###
GET http://zano-d17ae097.localhost.run/api/midtrans/test HTTP/1.1
###
GET http://zano-d17ae097.localhost.run/api/midtrans/test HTTP/1.1

### notif response
# {
#   va_numbers: [ { va_number: '55676053697', bank: 'bca' } ],
#   transaction_time: '2020-06-17 20:23:51',
#   transaction_status: 'settlement',
#   transaction_id: 'da997a46-bb88-4137-bd3e-aedfcd1d3f7f',
#   status_message: 'midtrans payment notification',
#   status_code: '200',
#   signature_key: '05deb38a686f0e1e701d68f869284ddd5c8ed53e745ff09f72718590c53239c60e3525b11867e4765dcdfd3273f7d6e4c03be65831ed1ef8e82f1d3416b493c6',
#   settlement_time: '2020-06-17 20:24:23',
#   payment_type: 'bank_transfer',
#   payment_amounts: [],
#   order_id: 'order-101c-1592400229',
#   merchant_id: 'G498255676',
#   gross_amount: '44000.00',
#   fraud_status: 'accept',
#   currency: 'IDR'
# }

# notif masuk
# {
#   va_numbers: [ { va_number: '55676053697', bank: 'bca' } 
# ],
#   transaction_time: '2020-06-17 20:23:51',
#   transaction_status: 'pending',
#   transaction_id: 'da997a46-bb88-4137-bd3e-aedfcd1d3f7f', 
#   status_message: 'midtrans payment notification',        
#   status_code: '201',
#   signature_key: '3b17b7ddbb607dfadfd519446294fcef6d83d5b74aadc977217205fd59d0cf4735711931269c1fa96169653f42ede27293f9b3e4b9853948c1b72edf52ded101',
#   payment_type: 'bank_transfer',
#   payment_amounts: [],
#   order_id: 'order-101c-1592400229',
#   merchant_id: 'G498255676',
#   gross_amount: '44000.00',
#   fraud_status: 'accept',
#   currency: 'IDR'
# }


# Transaction notification received. Order ID: 4dfd2c27-cf3c-422d-aea6-9e99b1d438d1. Transaction status: pending. Fraud status: accept.<br>Raw notification object:<pre>{
#   "va_numbers": [
#     {
#       "bank": "bca",
#       "va_number": "55676239337"
#     }
#   ],
#   "payment_amounts": [],
#   "transaction_time": "2020-06-19 20:48:30",      
#   "gross_amount": "5000000.00",
#   "currency": "IDR",
#   "order_id": "4dfd2c27-cf3c-422d-aea6-9e99b1d438d1",
#   "payment_type": "bank_transfer",
#   "signature_key": "08bd158155ad1c09b3a316f08ddae228edb42bca86872de51d095f71461baf7aaea96d7e01bd8fdbc7777a1c72db1197fa1f54b9935a231f864547a151918bf5",  "status_code": "201",
#   "transaction_id": "46105143-ada5-4b92-b6f2-1fc2f96a3628",
#   "transaction_status": "pending",
#   "fraud_status": "accept",
#   "status_message": "Success, transaction is found",
#   "merchant_id": "G498255676"
# }</pre>

Transaction notification received. Order ID: fdffddfafdff. Transaction status: expire. Fraud status: accept.<br>Raw notification object:<pre>{
#   "va_numbers": [
#     {
#       "bank": "bni",
#       "va_number": "9885567624806502"
#     }
#   ],
#   "payment_amounts": [],
#   "transaction_time": "2020-06-19 20:52:48",
#   "gross_amount": "5000000.00",
#   "currency": "IDR",
#   "order_id": "fdffddfafdff",
#   "payment_type": "bank_transfer",
#   "signature_key": "872e8c23145d1861dcf3fd3511c02e4250da0a26c8a75ef35d49fa16f9ac50078cc5f16229b2218ac5b0a3b2e4fd6bb26030558c9e2a6136d631cc803ed3fb0d",
#   "status_code": "407",
#   "transaction_id": "eb1bb3b4-1f43-4c81-bc8e-484457b717b7",      
#   "transaction_status": "expire",
#   "fraud_status": "accept",
#   "status_message": "Success, transaction is found",
#   "merchant_id": "G498255676"
