export const SET_USER = 'SET_USER'
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR'
export const SET_VENUES = 'SET_VENUES'
export const FETCH_VENUES = 'FETCH_VENUES'
export const SET_VENUES_ERROR = 'SET_VENUES_ERROR'
export const SET_VERIF_ERROR = 'SET_VERIF_ERROR'
export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR'
export const SIGN_OUT = 'SIGN_OUT'